// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'chartWrapper': string;
  'container': string;
  'heading': string;
}
declare const cssExports: CssExports;
export = cssExports;
